services:
  - type: web
    name: bookly
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
